receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'windows-exporter'
          scrape_interval: 10s
          static_configs:
            - targets: ['host.docker.internal:9182']
        - job_name: cadvisor
          scrape_interval: 10s
          static_configs:
            - targets: ['host.docker.internal:8880']

exporters:
  logging:
    loglevel: info
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:
  transform:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["hostname"], resource.attributes["hostname"])
          - set(attributes["env"], resource.attributes["env"])
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service_name, hostname, instance

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, transform]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp]
      processors: [resource]
      exporters: [logging, loki]

