{
 "title": ".NET Performance Counters",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "host", "label": "Host", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  {
   "title": "System.Runtime performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "GC Allocation Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_allocations_size{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_memory_usage{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(exported_job) (irate(process_cpu_time{hostname=\"$host\"}[1m])) * 100",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Number of GC Generations over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_collections_count{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}_{{generation}}"
    }
   ]
  },
  {
   "title": "TheadPool Completed Items Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_queue_length{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "JIT Compilation Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_jit_compilation_time{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "JIT IL Compiled Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_jit_il_compiled_size{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": ".NET Timer",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_timer_count{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "JIT Methods Compiled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_jit_methods_compiled_count{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": ".NET Assemblies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_assemblies_count",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "GC Generations Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_collections_count{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}_{{generation}}"
    }
   ]
  },
  {
   "title": ".NET Exceptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_exceptions_count{hostname=\"$host\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  }
 ]
}