{
 "title": "Windows Exporter Dashboard",
 "description": "Windows Exporter Dashboard",
 "tags": [
  "windows",
  "windows_exporter",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(windows_cpu_time_total,exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_os_time{exported_instance=~\"$server\"} - windows_system_system_up_time{exported_instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (exported_instance) (irate(windows_cpu_time_total{mode=\"idle\", exported_instance=~\"$server\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{exported_instance=~\"$server\"} - windows_os_physical_memory_free_bytes{exported_instance=~\"$server\"}) / windows_cs_physical_memory_bytes{exported_instance=~\"$server\"} * 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", exported_instance=\"$server\"}) by (exported_instance) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\", exported_instance=\"$server\"}) by (exported_instance)) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", exported_instance=\"$server\"}) by (exported_instance) * 100"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{exported_instance=\"$server\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "Hard Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{exported_instance=~\"$server\"} / windows_logical_disk_size_bytes{exported_instance=~\"$server\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{exported_instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{exported_instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{exported_instance=~\"$server\"}[5m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  windows_cs_physical_memory_bytes{exported_instance=\"$server\"}\n-\n  windows_os_physical_memory_free_bytes{exported_instance=\"$server\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{job=\"node\", exported_instance=\"$server\"}",
     "legendFormat": "memory free"
    },
    {
     "expr": "(\n  windows_os_paging_limit_bytes{job=\"node\", exported_instance=\"$server\"}\n-\n  windows_os_paging_free_bytes{job=\"node\", exported_instance=\"$server\"}\n)\n",
     "legendFormat": "paging used"
    },
    {
     "expr": "windows_os_paging_free_bytes{job=\"node\", exported_instance=\"$server\"}",
     "legendFormat": "paging free"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{exported_instance=~\"$server\"}[$interval]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent- Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_net_bytes_received_total{exported_instance=~\"$server\"}[$interval]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received- Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (mode) (irate(windows_cpu_time_total{exported_instance=~\"$server\", mode!=\"idle\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{exported_instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- irate(windows_logical_disk_read_bytes_total{exported_instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Flow Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{exported_instance=\"$server\"}[1h])) by (exported_instance)",
     "legendFormat": "Received-Download"
    },
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{exported_instance=\"$server\"}[1h])) by (exported_instance)",
     "legendFormat": "Sent-Upload"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{exported_instance=~\"$server\"}[$interval]) + irate(windows_net_packets_outbound_errors_total{exported_instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent-Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{exported_instance=~\"$server\"}[$interval]) + irate(windows_net_packets_outbound_errors_total{exported_instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received-Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Partitions Free Space",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{exported_instance=~\"$server\", volume !~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "free {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard disk i/o ops total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_split_ios_total{exported_instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "i/o {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_processes{exported_instance=\"$server\"}",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Services by state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{exported_instance=~\"$server\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "system_threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{exported_instance=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "({{process}} threads) ",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}