version: '3.7'
services:
  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - ./config/loki-local.yaml:/etc/loki/loki-local.yaml
      - ./loki_volume:/loki
    ports:
      - "3100:3100"
    command:
      -config.file=/etc/loki/loki-local.yaml
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus_volume:/prometheus
    ports:
      - 9090:9090
    command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--config.file=/etc/prometheus/prometheus.yaml'
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3001:3000
    volumes:
      - ./config/grafana_dashboards/:/etc/dashboards/
      - ./grafana_volume:/var/lib/grafana
      - ./config/grafana_provisioning/:/etc/grafana/provisioning/
    restart: unless-stopped
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./tempo_volume:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    restart: unless-stopped
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
    restart: unless-stopped
